name: icolosprod
channels:
  - psi4
  - conda-forge
  - defaults
  - rdkit
  - pytorch
dependencies:
  - biopython>=1.79
  - ipython
  - ipykernel
  - pip
  - python>=3.9
  - scikit-learn>=1.0.1
  - modal>=0.4
  - psi4>=1.4
  - pdbfixer
  - pydantic>=1.8
  - jsonschema
  - pyvis
  - requests
  - openbabel>=3
  - rdkit>=2021.09.2
  - acpype>=2022
  - openff-toolkit>=0.10.2
  - dill>=0.3.4
  - lomap2>=2.0.0
  - pygraphviz
  - pytorch
  - pip:
    - black
    - regex
    - peptidebuilder>=1.1
    - pytest
    - pytest-xdist
    - skorch>=0.11
